
version: 2.1
jobs:
  build:
    working_directory: ../
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh -p 22 $HOST_USERNAME@$HOST_IP "cd ~/MealSaver; git pull; pm2 start app.js";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build